### ISSUE TITLE
感觉你打印图片传输数据的这种方式是不是有问题

### ISSUE THREAD

**Issue by hechuanhua** [GitOfZGT/wx-bluetooth-print-demo#1]
你貌似是把图片的像素点分割成了一个一个Uint8Array，然后每个Uint8Array都push一个打印指令，这种方式就想到与一个像素点一个像素点去打印，打印1张图片感觉要几分钟，根本就没办法用在实际场景中。
看别人好像是全部指令和图片信息放在一起，然后分包传输

**Comment by GitOfZGT** [comment]
> 你貌似是把图片的预期点分割变成一个Uint8Array，然后每个Uint8Array都push一个打印指令，这种方式就想到与一个提示点一个替换点去打印，打印1张图片感觉要几分钟，根本就没办法用在实际场景中。
> 看别人好像是全部指令和图片信息放在一起，然后分包传输

这个看指令使用方式，打印机产商有对应的指令使用文档的，不是所有的打印指令都是同一标准的，案例中的打印指令传输方式是逐行分段打印，也是打印机产商建议的；而且，微信小程序打印图片慢，并不是打印机指令使用问题，我试过多种传输方式，并没有区别，在文中也有提到，打印图片慢的主要原因是微信小程序只能连低功率蓝牙，传输数据通道限制问题！
